### ISSUE TITLE
Allow devtools to run concurrently with Amok

### ISSUE THREAD

**Issue by caspervonb** [caspervonb/amok#100]
Previously discussed in #69, you cannot use devtools at the same time. I was being optimistic about the time frame it would be resolved internally as there was action happening on the ticket but It's taking too long and we need to take external action after-all.

#25 touches on implementing a multiplexing adapter for the chrome protocol, from what I've read on the node tracker they will be implementing the chrome protocol but only supporting a single agent (connection) which is another argument for implementing the multiplexer.

Now previously I couldn't figure out how to specify the web socket url for the internal chrome dev tools, looking at it today I'm not sure how i missed it, as you can pass it as a query parameter
```js
http://localhost:9222/devtools/inspector.html?ws=localhost:9223/devtools/page/BCC61D5D-4221-40B6-9BB9-6B0559F36CF9
```

Now there's still one minor limitation with this workaround, you can still not use the right click approach to inspect a page. You have to navigate to debug-host:debug-port and find the page there.

**Comment by caspervonb** [comment]
Work in progress, I should **really** be looking for a contract right now but feel like this is the last piece that's holding amok back from mass appeal.

![screen shot 2015-07-24 at 05 04 05](https://cloud.githubusercontent.com/assets/157787/8862239/99720c90-31c1-11e5-8d6e-4f7e5490874a.png)

What's going on here? Running our own http and web socket server, that broadcasts to all connected clients. So neither amok or devtools are connecting to the browser directly, but through the proxy/multiplexer.

![screen shot 2015-07-24 at 05 16 09](https://cloud.githubusercontent.com/assets/157787/8862444/24cf957c-31c3-11e5-984c-d40bd45f9362.png)

You still cannot, right click and choose inspect element, instead you'd navigate localhost:4000 (designated by another set of cli options) and click the target you want there.

Currently, it's working but unstable and tends to crash, posting an update to gauge interest.

**Comment by caspervonb** [comment]
These tabs, seem to work fine
* Elements
* Network
* Timeline
* Profiles
* Audits

There are some state issues with the source, and console tab
- Breakpoints do not display properly until the page is reloaded, seems fine after reloading once.
- Script modifications are not mirrored in the source view
- Console does not work until page is reloaded

**Comment by barneycarroll** [comment]
Hey @caspervonb, could you instruct about how to do this exactly? `/devtools/inspector.html?ws=localhost:9223` gives me a 404, and it's not clear what the rest of the query string your posted (`/devtools/page/BCC61D5D-4221-40B6-9BB9-6B0559F36CF9`) is about...

**Comment by caspervonb** [comment]
@barneycarroll Just navigate to `http://localhost:9222` and the index page from the screenshot is available which has clickable thumbnails which will take you to the inspector for your desired page.

The note in this issue was just the fact that the websocket address could be passed as a query parameter, basically allowing things to work.

**Comment by caspervonb** [comment]
Docs are sparse on it, but read this https://medium.com/@caspervonb/amok-and-external-developer-tools-9bcbddfd8f45#.y8dstjd4r

**Comment by caspervonb** [comment]
And the query string is just **host**:**port*/devtools/page/**page-id** but from a users perspective that should be totally irrelevant
