### ISSUE TITLE
I want to learn how amok works

### ISSUE THREAD

**Issue by stereokai** [caspervonb/amok#109]
Where should I begin? How to tie all the strings together?

My ultimate goal is to contribute :)

**Comment by caspervonb** [comment]
I was hoping for more localised questions but here it goes.

Amok is a debugger client, in that it connects to clients (browsers) through a remote debugging protocol, everything it does usually ties into the protocol in some way or another, altho there are exceptions like the server.

I use my own thin library ([node-rdbg](http://github.com/caspervonb/node-rdbg) to communicate via the [chrome debugging protocol](https://developer.chrome.com/devtools/docs/protocol/1.1/index), rationale for re-inventing the wheel here is that the one available is not very node like, I was preferring to have error first callbacks, etc.

At the core is [`amok.Runner`](../man/amok.Runner.3.md) which just handles a stack of middleware plugins, these plugins are run at initialization time before attempting to connect to the target client.
Everything else is *just a plugin* that hooks into the lifecycle events of either the connection or runner.

The binary is pretty much just a bunch of  `if option then use plugin` statements.

Other than that, help me, help you, ask specifics ;-)

**Comment by caspervonb** [comment]
Assuming we got it covered in chat

**Comment by stereokai** [comment]
In fact, I'd like to know how does amok know what code has changed (it gets the diff from the watcher?) and how does it know to update the correct code living in the browser. Don't need to close just yet! Just hadn't had the time to attend to this :)

**Comment by caspervonb** [comment]
Ups, sorry then, just trying to stay on top of these issues.

> I'd like to know how does amok know what code has changed

It just spin's up file watchers for the source file when the scripts are parsed on page load. Reload spins down the file watchers.

There's an internal map shared between the compiler and hot patcher plugins that maps urls to absolute file paths (stored via `runner.set('scripts, {})`) which lets us compile to a temporary file on disk so that the end user never has to see the temporary files. 

> how does it know to update the correct code living in the browser.
The diff and patch is done by V8, core of it is written in C++. We touched briefly on that in #92.

Re-evaluation is a different beast and since it's not even pushed to github yet I'll forego getting into that here.

**Comment by stereokai** [comment]
Thank you very much.

Re-eval is #79?

**Comment by stereokai** [comment]
Thank you very much. But wait. A couple of questions:

You're only telling V8: "here are the new JS files, do your magic!" and that's it? You don't need to pinpoint what's been changed and where it should go?

How is that internal map constructed? Do you follow script tags, `require()` calls, ES2015 `import`s, etc?

And lastly, re-eval is #79?

**Comment by caspervonb** [comment]
> You're only telling V8: "here are the new JS files, do your magic!" and that's it? You don't need to pinpoint what's been changed and where it should go?

Essentially yeah, just send it the script id and the new source through rdbg.

> How is that internal map constructed? Do you follow script tags, require() calls, ES2015 imports, etc?

Way simpler than that, this map is used in 3 plugins.
- hotpatch uses the map to lookup file paths.
- compiler sets the map to only contain the compiled script.
- server uses it to generate the appropriate script tags for the default index.html.

By default the map is set 1:1 to input scripts passed to the amok binary (https://github.com/caspervonb/amok/blob/master/bin/amok#L54-L57)

> And lastly, re-eval is #79?

Yes, I should note tho that #79 is additive and will run as an opt-in pass *after* the v8 patches.

**Comment by stereokai** [comment]
> Yes, I should note tho that #79 is additive and will run as an opt-in pass after the v8 patches.

What are the implications of that?

**Comment by caspervonb** [comment]
> What are the implications of that?

Just emphasising that this is will not be a replacement, but an additive feature.

**Comment by stereokai** [comment]
Oh, sure :) That I already know.

Also, I didn't know you could pass more than one script in the CLI API

**Comment by caspervonb** [comment]
Closing this, Fairly certain you're up to speed by now ;)

**Comment by stereokai** [comment]
@caspervonb I absolutely am :)
