### ISSUE TITLE
unclear whether this is a bug or intentional - probably needs a better console.log

### ISSUE THREAD

**Issue by Pomax** [caspervonb/amok#11]
Running amok (I see what you did there) I get the following output:
```
Attaching debugger...
Server listening on http://127.0.0.1:9966
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)
```
But there is no indication whether this is intentional behaviour with a console.log explaining why this is happening and how to mitigate it, or whether this is a bug that needs fixing asap.

**Comment by caspervonb** [comment]
It's happening when trying to connect to chrome, and chrome is not listening on 9222 (or the debuggerPort specified if not using the default)

**Comment by caspervonb** [comment]
The bug part of it should be fixed where the debugger was trying to connect before the browser was opened.

**Comment by caspervonb** [comment]
Should be covered by documentation now, a client with remote debugging enabled must either be launched beforehand or specified via the client option.
