### ISSUE TITLE
Possible pre-mature script evaluation for hot-swapping

### ISSUE THREAD

**Issue by dkornishev** [caspervonb/amok#132]
Started amok pointing to a browserify-babelify transpiled file.  When transpiler overwrites the target file, amok issues:
> LiveEdit Failure: Failed to compile new version of script: SyntaxError: Unexpected end of input 

Gulp task below for reference.

 ```js
gulp.task("watch", function() {
    var bundler = browserify({
        entries: ['./src/index.js'],
        transform: [transpile],
        debug: true,
        cache: {}, packageCache: {}, fullPaths: true // Requirement of watchify
    });

    var watcher  = watchify(bundler);

    return watcher
        .on('update', function () { // When any files update
            var updateStart = Date.now();
            watcher.bundle() // Create new bundle that uses the cache for high performance
                .pipe(source('index.js'))
                .pipe(gulp.dest('./build/js/'));
            console.log('Updated!', (Date.now() - updateStart) + 'ms');
        })
        .bundle() // Create the initial bundle when starting the task
        .pipe(source('index.js'))
        .pipe(gulp.dest('./build/js'));
});
```javascript

"babelify": "^6.1.2",
"browserify": "^10.2.4",
"vinyl-source-stream": "^1.1.0"

Windows 7 OS.

**Comment by caspervonb** [comment]
Watchify version? 3.x is broken, use 2.6

**Comment by caspervonb** [comment]
Just to put it on edge, when you're streaming with libraries and tools that act like browserify, that process and stream and the same time you are essentially doing this

```js
setInterval(function() {
  fs.appendFile('filename.js', nextChunk);
}, 2500);
```

There's no way for amok to deal with this in a sane manner, the producer really has to write the entire file in one go.

**Comment by dkornishev** [comment]
I figured it was something like that.

**Comment by caspervonb** [comment]
Not entirely sure how to deal with this while keeping it "gulpy", so if you could please post your solution :grin:
