### ISSUE TITLE
Can't attach to debugger in Windows

### ISSUE THREAD

**Issue by jamietre** [caspervonb/amok#134]
Windows 7, using cygwin/mintty, but also tried it in a normal console and same thing.

No problem installing (by omitting optional deps) but I can't get it to run. Command line parms are to be sure I'm being as explicit as possible. Chrome debugger is definitely running, responds on port 9222.

    > amok bundle.js --no-bundler --debug-port 9222 --debug-host localhost 

    connecting to undefined
    events.js:85
          throw er; // Unhandled 'error' event
                ^
    TypeError: Parameter 'url' must be a string, not undefined
        at Url.parse (url.js:110:11)
        at Object.urlParse [as parse] (url.js:104:5)
        at WebSocket.initAsClient (C:\users\jtreworgy\appdata\roaming\npm\node_modules\amok\node_modules\ws\lib\WebSocket.js:550:23)
        at new WebSocket (C:\users\jtreworgy\appdata\roaming\npm\node_modules\amok\node_modules\ws\lib\WebSocket.js:74:18)
        at Function.connect (C:\users\jtreworgy\appdata\roaming\npm\node_modules\amok\node_modules\ws\index.js:42:16)
        at Client.connect (C:\users\jtreworgy\appdata\roaming\npm\node_modules\amok\node_modules\rdbg\lib\index.js:220:19)
        at C:\users\jtreworgy\appdata\roaming\npm\node_modules\amok\lib\index.js:74:14
        at IncomingMessage.<anonymous> (C:\users\jtreworgy\appdata\roaming\npm\node_modules\amok\node_modules\rdbg\lib\index.js:328:16)
        at IncomingMessage.emit (events.js:129:20)
        at _stream_readable.js:908:16

I tried to troubleshoot, here's a bit of info from `Runner.prototype.connect`

    Runner.prototype.connect = function (port, host, callback) {

port = 9222, host = localhost

    rdbg.get(port, host, function (error, targets) {

`runner.get('url')` ==  http://localhost:9966/    ...*this seems strange*

url properties from each target in targets array:

-- url: chrome-extension://nckgahadagoaajjgafhacjanaoiihapd/panel.html?gtn_4qs3ef
-- url: https://www.google.com/?gws_rd=ssl  ...*this is the url of the browser*
-- url: chrome-extension://pafkbggdmjlpgkdkcbjmhmfcdpncadgh/_generated_background_page.html
-- url: chrome-extension://nckgahadagoaajjgafhacjanaoiihapd/_generated_background_page.html
-- url: chrome-extension://jafmfknfnkoekkdocjiaipcnmkklaajd/_generated_background_page.html
-- url: chrome-extension://iphcomljdfghbkdcfndaijbokpgddeno/_generated_background_page.html
-- url: chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/background.html
-- url: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/_generated_background_page.html
-- url: chrome-extension://gbkffbkamcejhkcaocmkdeiiccpmjfdi/background.html
-- url: chrome-extension://eeocglpgjdpaefaedpblffpeebgmgddk/background.html
-- url: chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/background.html

Hope that helps.

**Comment by jamietre** [comment]
Closing (for now) -- i was following trivial instructions elsewhere rather than the readme :) I think I got this

**Comment by caspervonb** [comment]
From where? (very ancient information)

**Comment by jamietre** [comment]
It just seemed so easy that I read no further :)

http://caspervonb.com/javascript/tools/live-edit-javascript-amok/

**Comment by caspervonb** [comment]
> It just seemed so easy that I read no further :)

Ups I've been neglecting my blog and whatnot for some time, so busy with amok :)

Good news is that it's even easier now than whats in that blog post (see [getting_started](http://amokjs.com/getting_started.html))

**Comment by jamietre** [comment]
No worries, it's working better already when I turned off my tunnel vision!

**Comment by caspervonb** [comment]
Great! :+1:
