### ISSUE TITLE
Webpack hot module replacements and a webpack loader

### ISSUE THREAD

**Issue by caspervonb** [caspervonb/amok#136]
Continuation of #92 

**Do we need to use webpack-dev-server to use webpack hot module replacements?**
Short answer, **no**

Calling webpack with the hot option
```
$ webpack entry.js --hot
```

Produces HRM scripts and manifest in the `--records-path`, these can then be polled and downloaded via the module.hot API, as long as these files can be found on the server it should *just work* when polled for an update.

Webpack dev server seems to be there in order to, keep it in memory and provide the socket connection to push updates, instead of polling.

With amok however, we already have a web socket connection, we already have events which fire when the bundle has been patched, for example, the following will work today, with amok's server or any arbitrary http server.

```sh
$ amok index.js --compiler webpack --browser chrome --hot -- --hot
```

```js
document.body.innerHTML = 'asd';

if (module.hot) {
  console.log('hot enabled');
  module.hot.accept();

  window.addEventListener('patch', function() {
    if (module.hot.status() !== 'idle') {
      return console.log('Not idle, eek!');
    }

    module.hot.check(function(error) {
      if (error) {
        console.error(error);
      }

      console.log('apply');
      module.hot.apply();
    });
  });

  module.hot.dispose(function() {
    console.log('dispose');
  });
}
```

So if you want to use HRM with amok, its that easy.

As a side note, I was playing around with webpack-dev-server and it really spits out a lot of debugging information about itself, my own logging calls were being drowned in them, what happened to silent by default...

----

**Should we use HRM?**
Probably **not**

While this was my initial intention (like, this morning), it's quite literally a backwards way of doing it. Instead of patching the current module with new properties, we would be patching the new module with the previous changes. @jlongster goes over some of this in [this post](http://jlongster.com/Backend-Apps-with-Webpack--Part-III). Also HRM gives you the evaluation results not the source code so we have no say in side effects.

I'll get back to the details on the proposed inline patcher later.

**Comment by caspervonb** [comment]
As for the patcher/dispatcher, we should be able to get away with getting the functions that contain the modules, should be searching for the node in question but for webpack outputting commonjs, the following works.

```js
var esprima = require('esprima');
var cache = require.cache;

window.addEventListener('patch', function(event) {
  var source = event.detail.source;
  var ast = esprima.parse(source, {
    range: true,
  });

  var nodes = ast.body[0].expression.arguments[0].elements.map(function(node) {
    return node.body;
  });

  nodes.forEach(function(node, id) {
    var module = cache[id];
    if (module && module.exports.__apply__) {
      module.exports.__apply__(source, node);
    }
  });
});
```

The transform would inject an __apply__ export into every module, giving us an access point with its lexical scope to re-evaluate what we want and its all done via the extension hooks so there are literally no changes required to amok core.

**Comment by gaearon** [comment]
Can this be implemented as a Babel plugin? (Sorry if it's a silly question. :-)

**Comment by caspervonb** [comment]
> Can this be implemented as a Babel plugin? (Sorry if it's a silly question. :-)

Hmph, I'm not sure how to do it with babel alone, because we don't get a module environment from it so it might be better to just leave it to browserify/webpack/requirejs and systemjs plugins.

**Comment by caspervonb** [comment]
@gaearon TL;DR. **Yes**, should be doable.

Actually, knowing that amok already patches everything, we can throw data into properties under compilation.

This means, if we define the AST as a property on the module itself or as a function within the module, we can quite easily track it and diff it without having to include esprima or acorn into the runtime environment (they're quite huge and negatively impacts hot patching perf big time).

So scrapping the above dispatching, and instead embedding the AST we can have a transform that looks something like this.

```js
// loader.js
var fs = require('fs');
var path = require('path')
var esprima = require('esprima');

module.exports = function(source, map) {
  var ast = esprima.parse(source);
  source += [
    'function __ast() {',
    '  return ' + JSON.stringify(ast) + ';',
    '}',
  ].join('\n');

  source += fs.readFileSync(path.resolve(__dirname, 'inject.js'), 'utf-8');

  return source;
};
```

Which we can diff quite easily in client code

```js
// inject.js
(function() {
  var diff = require('diff');

  var previous = __ast();
  window.addEventListener('patch', function(event) {
    console.log('post-patch evaluation');

    var current = __ast();
    var changes = diff.diffJson(previous, current).filter(function(change) {
      return change.added;
    });

    changes.forEach(function(change) {
      var node = change.value;
      
      // the fun part starts here. TBD
    });

    previous = current;
  });
})();
```

**Comment by caspervonb** [comment]
Continuing with my brain dump, there's one major caveat, there simply is no way to declare local variables in a scope past its initial execution. However since we're implementing this through transforms for bundlers we can just transform that.

```js
var THINGS = {
}:

console.log(THINGS);
```

Would be transformed into an object, so that it can be mutated.

```
var locals = {};
locals.THINGS = {
};

console.log(locals.THINGS)
```

**Comment by caspervonb** [comment]
Continued in https://github.com/caspervonb/amok-loader/issues/ for anyone interested in unstructured R&D postings

**Comment by caspervonb** [comment]
A draft is currently at https://github.com/caspervonb/amokify

There are two special things that need to be dealt with beyond the transform, module definitions need to be returned from a function, and the order of the functions need to be stable, with new modules added at the bottom.

Beyond that, it's all portable.
