### ISSUE TITLE
unable to run with react-router

### ISSUE THREAD

**Issue by hyusetiawan** [caspervonb/amok#138]
though amok almost magically made it all work, so close. I have found an issue when
using react-router, the typical installation and setup.

As long as I am changing index, it would work, things would refresh and all (though it would complain sometimes that React is undefined) 

It happens whenever i navigate away from the index, the show stopper is that I am getting this:
`
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op.
`
and things would stop getting rerendered, and this is how i rerender my react app:

```
Router.run(App.routes, Router.HistoryLocation, function(Root){
    React.render(React.createElement(Root), document.body);
});


window.addEventListener('patch', function(event) {
    Router.run(App.routes, Router.HistoryLocation, function(Root){
        React.render(React.createElement(Root), document.body);
    });
```

Is there a better way to use it with react-router?

**Comment by caspervonb** [comment]
That warning is from `Router.run`, yes?

Ping @ryanflorence @mjackson

**Comment by gaearon** [comment]
I don't think you should ever `Router.run` twice.

Try something like this?

```js
var lastRoot;
function renderApp() {
  React.render(React.createElement(lastRoot), document.body);
}

Router.run(App.routes, Router.HistoryLocation, function(Root){
  lastRoot = Root;
  renderApp();
});

window.addEventListener('patch', function(event) {
  renderApp();
});
```

**Comment by hyusetiawan** [comment]
@gaearon I just tried it, it works, in that the app rerenders, however the warning about setState still being emitted repeatedly (just like before) without Amok of course this does not happen.

@caspervonb any hint on the setState warning? This happens only when I change the url and after a while it would stop emitting the warning (approx after 25 warnings) I am thinking this happens because of some sort of race condition?

**Comment by caspervonb** [comment]
React came about at a time when I'm doing lower level things (like amok), so while I'm somewhat familiar with react's core I am not familiar with all the community tooling and plumbing.

I don't think its anything specific to amok or v8.setScriptSource tho, as it does nothing after all :wink: 
Quick test to eliminate amok from the problem, run a simple setInterval re-rendering with react-router without amok.

E.g taking @gaearon's example

```js
var lastRoot;
function renderApp() {
  React.render(React.createElement(lastRoot), document.body);
}

Router.run(App.routes, Router.HistoryLocation, function(Root){
  lastRoot = Root;
  renderApp();
});

setInterval(function() {
  renderApp();
}, 60/1000);
```

**Comment by stereokai** [comment]
@hyusetiawan Please update us. We are listening.

**Comment by hyusetiawan** [comment]
the provided solution works for me and for completeness's sake here is the command that I used to run it:
amok --hot --browser chrome --compiler watchify src/public/js/bootstrap.js -- --delay 1 --transform babelify ----fast http://localhost:3000/

**Comment by caspervonb** [comment]
:+1:
