### ISSUE TITLE
passing parameters

### ISSUE THREAD

**Issue by hyusetiawan** [caspervonb/amok#141]
How do I pass parameters to the --compiler options?
Specifically I want to change the default delay of watchify of 600 ms to something faster.
this is my attempt:
` amok --hot --browser chrome --compiler watchify --delay 1 src/public/js/bootstrap.js --transform babel --fast`

but the delay is still quite long from typing to refreshing and this is still a hello world app, I am guessing is that --delay 1 is not being honored.

**Comment by caspervonb** [comment]
```sh
$ amok --hot --browser chrome --compiler watchify src/public/js/bootstrap.js -- --delay 1 --transform babel --fast
```

**Comment by hyusetiawan** [comment]
running:
`amok --hot --browser chrome --compiler watchify src/public/js/bootstrap.js -- --delay 1 --transform babel --fast `
gives me an error: 
`Error: Unexpected object exported by the "/Users/www/Projects/DemoApp/node_modules/babel/index.js" package. Expected a transform function.`

Along with that I would like to specify which url to go, ex: 
`amok --hot --browser chrome http://localhost:3000/example`
this works fine but when I want to combine it with the compiler and transform like so:
`amok --hot --browser chrome --compiler watchify src/public/js/bootstrap.js  --transform babel http://localhost:3000/example`
I would get the following error message:
`
Error: Cannot find module '/Users/www/Projects/DemoApp/http:/localhost:3000/example' from '/Users/www/Projects/DemoApp'
`

I don't know the order or syntax to describe:
open http://localhost:3000/example, watch src/public/js/bootstrap.js using watchify with delay of 1ms and transform using babel with fast parameter

I feel like it would be easier if amok has a config file instead :)

**Comment by caspervonb** [comment]
The babel transform is called babelify is it not?

**Comment by hyusetiawan** [comment]
@caspervonb i installed babelify and changed the parameter, it works, including opening a specific URL
I am not sure why the first command that uses babel did not complain about babel vs babelify.

**Comment by caspervonb** [comment]
The first command did not complain because amok was getting the --transform option, unknown arguments are ignored.
