### ISSUE TITLE
Accept an url to an existing server

### ISSUE THREAD

**Issue by caspervonb** [caspervonb/amok#16]
In order to work with other stacks, we should be able to accept a path to an existing server. In this mode amok would serve as a debugger only and not a debugger/server.

Still keeping around the quick launch feature, it's handy for running tests and frontend apps.

So usage would be changed to `[options] [files] | [url]`

**Comment by lookfirst** [comment]
Specifically, I'd like to see this integrated with browserSync instead of being its own server. https://github.com/BrowserSync/

Maybe amok could just be a middleware instead?

**Comment by caspervonb** [comment]
@lookfirst What exactly do you mean by middleware? Amok has no place in the server stack

**Comment by lookfirst** [comment]
@caspervonb I mean that instead of having your own http server, you use the one that is provided by browserSync. This could be added to bS through a [middleware layer](http://www.browsersync.io/docs/options/#option-server).

**Comment by caspervonb** [comment]
Feel free to open an issue, describing what the potential gains are etc.
