### ISSUE TITLE
Running any amok command produces an error

### ISSUE THREAD

**Issue by gstanislav** [caspervonb/amok#160]
Fresh install. Node v4.0.0

Produced error: `env: node\r: No such file or directory`

**Comment by caspervonb** [comment]
I've unpublished 1.1.4. I published it from windows with windows line endings resulting in shebang comments being broken.

Installing again will give you 1.1.3 and should resolve this. I'll get 1.1.5 out soon.

**Comment by caspervonb** [comment]
Sorry for the inconvenience, Windows quicks are somewhat alien to me ;)
