### ISSUE TITLE
'change' event

### ISSUE THREAD

**Issue by barneycarroll** [caspervonb/amok#162]
'change' is a bad choice because it is a native DOM form input event which will necessarily bubble up to the window. Perhaps an `amok-` prefix for these custom events?

**Comment by caspervonb** [comment]
Ups, yeah good call. Maybe call it `watch`?

**Comment by caspervonb** [comment]
So I'll be renaming the events to be have more descriptive names.

* scriptChange
* fileChange

**Comment by barneycarroll** [comment]
Cool. `scriptChange` being the new `patch`?

**Comment by caspervonb** [comment]
Correct :+1:

**Comment by caspervonb** [comment]
It'll go out in 2.0 (https://github.com/caspervonb/amok/commit/74956c2e16671e5e69673d040670b0e1cc197758) currently on master, but I have some more things I want to break before pushing out a major. 

In the meantime you can test for `detail` which indicates that its a custom event, and you can be pretty sure its not a DOM event.
