### ISSUE TITLE
Fundraiser

### ISSUE THREAD

**Issue by caspervonb** [caspervonb/amok#17]
There's a bounty source [fundraiser](http://bit.ly/18BJ1fI) going on, please spread the word :smile:

**Comment by fibric** [comment]
Here is my help
https://www.bountysource.com/teams/amok/backers

**Comment by caspervonb** [comment]
@fibric sweet! thank you very much :+1:

**Comment by caspervonb** [comment]
@mkatrenik thank you very much :smiley_cat:

**Comment by gaearon** [comment]
:+1:

**Comment by caspervonb** [comment]
@gaearon thanks man :grin:

**Comment by okonet** [comment]
:+1:

**Comment by caspervonb** [comment]
Alot of pledges the past couple of days, you rock guys +1

**Comment by caspervonb** [comment]
@okonet Thank you for pledging :smile:

**Comment by caspervonb** [comment]
Last stint, down to 48 hours or so left :hourglass_flowing_sand:

**Comment by caspervonb** [comment]
I'm happy to be able to say that we made the goal :+1: Thanks to everyone for contributing!
