### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by nmn** [caspervonb/amok#2]
Would love to know more about how to transition from a watchify project to amok.

**Comment by jiyinyiyong** [comment]
Need docs... I don't know what to do seeing this error:
```
➤➤ amok main.js
Server listening on http://127.0.0.1:9966

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
```

**Comment by caspervonb** [comment]
@mnm Basically, `--` stops argument parsing, so any arguments following that will be passed to the spawning of the compiler/bundler set in the environment variable `BUNDLER`.

For example
```
export BUNDLER="watchify"
amok app.js -- -t coffeeify 
```

@jiyinyiyong That error would indicate there is no chrome client it can connect to available.

Documentation is basic, time will aid with that.
Feel free to jump on the [gitter chat](https://gitter.im/caspervonb/amok) if you have any further issues getting started.

**Comment by caspervonb** [comment]
Closing this as it is very generic, again for support I'm available via the [gitter chat room][https://gitter.im/caspervonb/amok] on a regular basis. 

The documentation will improve with time as i understand more of what isn't obvious to users and what they are having trouble with.

Thanks, Casper
