### ISSUE TITLE
Document usage with Webpack and Browserify

### ISSUE THREAD

**Issue by gaearon** [caspervonb/amok#27]
Some ready-to-go recipes would help.

**Comment by caspervonb** [comment]
On this note, I know you're running a mac @gaearon, is it normal to have an super weird and long path to spawn chrome?

**Comment by gaearon** [comment]
Normally it's Applications Google Chrome something resources something Google Chrome?

**Comment by caspervonb** [comment]
I don't own one so i wouldn't know :smile:

**Comment by okonet** [comment]
@caspervonb it is `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome`

**Comment by jeffling** [comment]
@caspervonb does this work with multiple bundles generated by webpack?

**Comment by caspervonb** [comment]
When using a compiler it is assumed there will be a single output.
If you run webpack separately and give amok the output files instead it will map and watch them directly.

**Comment by jeffling** [comment]
@caspervonb thanks for the prompt answer. Will we be able to take advantage of webpack-dev-server and amok somehow? For example link amok directly to the running webpack-dev-server?

**Comment by caspervonb** [comment]
Plan on adding a url as an entry point (#16), which would get the files to watch via the page instead of passing them in manually.

But for now, it's not super clean at the moment, but just let amok spawn it's server and totally ignore it.
Should work since the server has no active part in the debugging session.

**Comment by george-norris-salesforce** [comment]
+1 for adding Browserify documention..

**Comment by caspervonb** [comment]
The gist of it, just build as normal and let amok act as a file watcher/script updater.
