### ISSUE TITLE
Getting Amok to run on Windows 7

### ISSUE THREAD

**Issue by cachaito** [caspervonb/amok#30]
Does anybody manage to install Amok on Windows 7 64 bit machine? If so, please tell me what did You install first :-)

**Comment by caspervonb** [comment]
Any details of what did not work?

**Comment by cachaito** [comment]
Hi Capser, sorry for late response. 
My config is: Win7 64bit, Node v0.12.1.
Problem is with Amok installation (with admin rights), which gives me [output](https://dl.dropboxusercontent.com/u/58104633/amok_log.txt)
I'm suspecting problem with node-gyp.

PS. I would reccommend nice windows [Console2](http://sourceforge.net/projects/console/) for CMD replacer ;-)

**Comment by caspervonb** [comment]
Alright those are from the `ws` module, and they are marked optional dependencies so even tho it looks like a failure i *think* it should be fine, optionally add `--no-optional `

**Comment by cachaito** [comment]
With `--no-optional` flag Amok installation looks much better now. Anyway I still have trouble with running amok with my yours canvas.js

Maybe I'm doing something wrong? My steps:
1. npm amok -g --no-optional
2. SET AMOK_CLIENT=%programfiles(x86)%\Google\Chrome\Application\chrome.exe --remote-debugging-port=9222
3. amok canvas.js
4. [log ](https://dl.dropboxusercontent.com/u/58104633/amok_start_log.txt) :-(

**Comment by caspervonb** [comment]
#31 and #26

Try wrapping the executable path in quotation marks so it will be left intact, spaces are treated as delimiters for arguments

**Comment by cachaito** [comment]
Casper something is wrong with those quotation marks. I tried diffrend combinaton like:
1. '"C:\Program Files\Google\Application\chrome.exe" --remote-debugging-port=9222'
2. "C:\Program Files\Google\Application\chrome.exe --remote-debugging-port=9222"
3. 'C:\Program Files\Google\Application\chrome.exe --remote-debugging-port=9222'
and:
4. "C:\Program Files"\Google\Application\chrome.exe --remote-debugging-port=9222
even:
5. "C:\Program Files\Google\Application\chrome".exe --remote-debugging-port=9222

All those combinations come to one error: 
``Error: spawn C:\Program ENOENT``

**Comment by caspervonb** [comment]
Alright thanks for the report, I'll get a VM running to do first hand testing on windows :+1:

**Comment by caspervonb** [comment]
You could add the chrome folder to the PATH env variable tho, then just do chrome.exe

**Comment by cachaito** [comment]
Ok, I did like You said: added system variable: `AMOK_CLIENT = chrome.exe --remote-debugging-port=9222` and now after: amok canvas.js --verbose
```
Starting server...
Server listening on http://127.0.0.1:9966
Spawning client...
Attaching debugger...
```
Chrome is starting with Yours canvas.js script and ball is start to bounce.... but.....
Every change in code in Sublime Text have no impact on Chrome window :-(

**Comment by caspervonb** [comment]
Hang on, got a VM running will figure out whats going on.

**Comment by xgrommx** [comment]
Hi @caspervonb I have the same problem as @cachaito. I have configured how you said, but I got this:

amok app.js --verbose
Starting server...
Server listening on http://127.0.0.1:9966
Spawning client...
Attaching debugger...
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: connect ECONNREFUSED 127.0.0.1:9222
    at Object.exports._errnoException (util.js:749:11)
    at exports._exceptionWithHostPort (util.js:772:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1009:14)

**Comment by caspervonb** [comment]
There's one tiny issue left (#41), but its working if no compiler gets specified

**Comment by caspervonb** [comment]
And it is fixed as of v0.12.3

**Comment by cachaito** [comment]
Hello again Casper!

I have tested v0.12.3 on my system. Here are my conclusions. Hope I won't let Your mood down :-P

First noticeable thing: `amok canvas.js -verbose` currently doesn't open a Chrome (AMOK_CLIENT is still in system variables, nothing have changed). Instead there is an error: 
```
Starting server...
Server listening on http://127.0.0.1:9966
Attaching debugger...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)
```
Ok, I overcame this situation with manually opening Chrome with `--remote-debugging-port=9222` flag. When browser *AND* tab with address: `http://localhost:9222/` are opened , then `amok canvas.js -verbose` gives nice:
```
Starting server...
Server listening on http://127.0.0.1:9966
Attaching debugger...
Debugger attached to Inspectable pages
File watcher ready
```
Unfortunately, every change in the canvas.js gives:
```
D:\Projekty\Minefield\try_catch_test\canvas.js changed
Re-compiling canvas.js ...
Unknown script canvas.js
```
No change on `http://localhost:9966/` - what a bummer :-(

**Comment by caspervonb** [comment]
So the conclusion here is pre 0.12.x everything was broken and after 0.12.x its really simple, right? :dancer:

**Comment by cachaito** [comment]
Let's assume that  0.12.x its really simple :ok_hand:
