### ISSUE TITLE
Windows gets stuck on starting watcher

### ISSUE THREAD

**Issue by caspervonb** [caspervonb/amok#39]
The ready event never gets fired and the process silently exits.
In this case the entry point is a single file in `%HOME%`, I'll assume it tries to recursively watch everything and just flat out crashes while attempting it, won't be a huge issue but should be resolved. Will work with a reasonable amount of files however.

Watching the actual script files instead works, but when watching the files directly  the change event only gets fired once (at-least with watchify@2.6 as the compiler), touching the file emits the event but watchify 2.6 atleast does not touch the file, rather it renames it.

Watchify@3.0 writes to it without a temporary file but there's issues there also

**Comment by caspervonb** [comment]
@mattdesl Might want to track this issue.

**Comment by mattdesl** [comment]
hmm.. I'm thinking of switching to watchify API instead of relying on the CLI. This would avoid the second chokidar instance on the bundle.js itself.  see [budo#20](https://github.com/mattdesl/budo/issues/20)
