### ISSUE TITLE
Halts with coffeescript as the compiler

### ISSUE THREAD

**Issue by acidsound** [caspervonb/amok#44]
Hi, @caspervonb. Thanks for your awesome work!
I tried like this.
```
$ amok -v -i --client chrome --compiler coffeescript canvas.coffee
```
but it hanged. I'm using coffeescript 1.9.1

**Comment by caspervonb** [comment]
Post the log output please :grin:

**Comment by caspervonb** [comment]
It's a bug, forgot to add --compile when invoking `coffee`, so its hanging waiting for the file to be compiled.

I'll try to get a fix out today.

**Comment by acidsound** [comment]
It works! :+1: 
but still has some trouble when edited.
https://github.com/jashkenas/coffeescript/issues/3863
I downgraded coffeescript version from 1.9.1 to 1.9.0. it works fine :100:
