### ISSUE TITLE
Error: not found: watchify

### ISSUE THREAD

**Issue by barneycarroll** [caspervonb/amok#48]
When I attempt to run the basic browserify command I get an error about watchify not being found:

```log
$ amok --client chrome --compiler browserify app.js

/usr/local/lib/node_modules/amok/node_modules/which/which.js:80
  throw new Error("not found: "+cmd)
        ^
Error: not found: watchify
    at Function.whichSync [as sync] (/usr/local/lib/node_modules/amok/node_modules/which/which.js:80:9)
    at Object.compile (/usr/local/lib/node_modules/amok/index.js:56:27)
    at /usr/local/lib/node_modules/amok/cmd.js:46:27
    at /usr/local/lib/node_modules/amok/node_modules/temp/lib/temp.js:231:7
    at Object.oncomplete (fs.js:107:15)
```

Installing watchify as a global or local devDependency doesn't seem to help. Any ideas?

**Comment by barneycarroll** [comment]
OK, my mistake. I'm used to the Gulp-/Grunt-style build philosophy whereby everything you need for your iterative development harness is stored as a devDependency *in your project source*. The solution is to install watchify and babel as global dependencies.

Seeing as these are from the preset configurations, it might be worth introducing custom try catches to inform the user they need these in their $PATH – a lot of people operate entirely within the node environment and might not understand (as I didn't) that requests for node module X isn't looking in their local '/node_modules' folder.

**Comment by caspervonb** [comment]
I have `node_modules/.bin` prepended in my path permanently, just makes things easier.
Otherwise on a per session basis, use `export PATH=$PATH:$(npm bin)`

**Comment by barneycarroll** [comment]
> This turned out to be false, right?

I think so, I was testing too many things at once without really understanding them and not taking note of all the environment changes I was making to get it to work. 

The per-session tip is interesting. I'm still trying to formalise the distinction between build & dev dependencies. Amok wouldn't be a development dependency of the project it helps develop, but the compiler probably would be.
