### ISSUE TITLE
Use amok programatically

### ISSUE THREAD

**Issue by bichotll** [caspervonb/amok#56]
Firstly - just say - awesome project!

Is there any way to run Amok programmatically on a node script?
I've checked the examples and related and I have not found anything about it, at least yet. It would be great to run it with our gulp/grunt scripts.

Cheers,
jaume

**Comment by caspervonb** [comment]
Thanks!

The API is not documented *yet* on purpose to discourage people from trying to depend on it, I will follow semver but leading up to 1.x things may break, a lot.

**Comment by bichotll** [comment]
Cool! I'll follow this up then ;)

**Comment by caspervonb** [comment]
You could of course implement it via a spawn type task, CLI will be fairly stable.

**Comment by bichotll** [comment]
Ugh...I don't know what you exactly mean heh
Can you give a clue? :p

**Comment by damassi** [comment]
@bichotll, something like this pseudo-code: `cmd.run('amok --client chrome --compiler webpack canvas.js', function() {
   console.log('works');
})`

**Comment by bichotll** [comment]
Cool! I'll try it out then! ;)

**Comment by caspervonb** [comment]
Yeah `child_process.spawn` or `gulp-spawn`

**Comment by caspervonb** [comment]
Pending on #78

**Comment by caspervonb** [comment]
API has landed, closing.
