### ISSUE TITLE
Look into jspm

### ISSUE THREAD

**Issue by caspervonb** [caspervonb/amok#57]
As mentioned in #53

**Comment by caspervonb** [comment]
@forresto what exactly are the challenges faced with jspm? what prevents it from working?

**Comment by forresto** [comment]
I have yet to try it... just curious if the concepts are compatible.

**Comment by caspervonb** [comment]
Closing this as a non issue then.

**Comment by barneycarroll** [comment]
AFAICT Amok has no opinions on package management. You can use NPM, Bower, JSPM or whatever other package repository or management system. Amok simply watches the filesystem for changes, optionally runs a compiler, and reloads code in the browser.
