### ISSUE TITLE
integrate with browserSync

### ISSUE THREAD

**Issue by lookfirst** [caspervonb/amok#60]
I already run a [browserSync](http://www.browsersync.io/) server to do my development. 

I'd love hot code swapping to be available within that server instead of having to use yours. 
I don't need the automatic recompile since that is part of my own workflow. 
I just need the hot code swapping.

It would probably be easiest to implement this through a middleware layer that lives within the request chain.

**Comment by caspervonb** [comment]
Alright was a bit thrown off by the middleware talk, so a lot of things in amok are optional, it actually doesn't care about the server at all except for the url in the tab it connects to, #16 makes it official, a single url can be used as the entry point. (theoretically it could be a file url, haven't tested that tho)

So, once 0.13 gets pushed out you can do
```sh
browser-sync --server --host localhost --port 9999 ...
amok --client chrome http://localhost:9999
```

Got a couple of more things to get into 0.13 before i push it out tho

**Comment by barneycarroll** [comment]
@lookfirst thought you might be interested in this ;) — my angle (perpetual quest to reduce interoperability complexity) is that Amok should effectivel obviate browsersync.

**Comment by lookfirst** [comment]
I see it as the other way around since bS does more. In my mind, amok should do one thing well, hot code reloading.

**Comment by caspervonb** [comment]
0.13.x was released a day or two ago, url is a valid entry point, should be fairly simple to interop via just executables. browsersync can run as a proxy too.

**Comment by caspervonb** [comment]
Closing this as there's been no value proposition.

**Comment by barneycarroll** [comment]
Regardless of perceived value, it's possible. @lookfirst any ideas of what a simple demo could look like? I imagine CSS preprocessing + Amok script reloading? Could do a simple Bootstrap app, maybe?

**Comment by lookfirst** [comment]
I was playing around with amok and then ran into issue #62 ... I haven't gotten a chance to play around since it has been fixed. Once I get a better handle on how things are working, maybe I can come up with something.
