### ISSUE TITLE
Strange error on windows machine

### ISSUE THREAD

**Issue by webcss** [caspervonb/amok#61]
Hi, trying to run amok on my machine I get a strange error: 
error client: [3268:3504:0410/114818:ERROR:bluetooth_adapter_win.cc(102)] NOT IMPLEMENTED

Specs: Windows 8.1, Chrome 43.0.2357.10 dev-m 64bit, node v0.12.2

**Comment by caspervonb** [comment]
Should be safe to ignore, it's from chrome's diagnostic log.

**Comment by webcss** [comment]
Ok, thanks
