### ISSUE TITLE
Problem when trying to attach to existing chrome

### ISSUE THREAD

**Issue by marekventur** [caspervonb/amok#63]
I'm using Chome 42.0 on OSX with amok 0.13.8.

Chrome is running and listening to 9222, I can see the correct page when I go to "localhost:9222", but amok errors when I try to start it:
```
marek the_heist $ lsof -n -i4TCP:9222 | grep LISTEN
Google    85738 marek   86u  IPv4 0x61a795575e302c33      0t0  TCP 127.0.0.1:teamcoherence (LISTEN)
marek the_heist $ amok static/build/index.js --no-bundler

/Users/marek/.nvm/v0.10.27/lib/node_modules/amok/node_modules/rdbg/index.js:100
    var socket = ws.connect(target.webSocketDebuggerUrl);
                                  ^
TypeError: Cannot read property 'webSocketDebuggerUrl' of undefined
    at ChromeConnection.attach (/Users/marek/.nvm/v0.10.27/lib/node_modules/amok/node_modules/rdbg/index.js:100:35)
    at /Users/marek/.nvm/v0.10.27/lib/node_modules/amok/index.js:254:12
    at IncomingMessage.<anonymous> (/Users/marek/.nvm/v0.10.27/lib/node_modules/amok/node_modules/rdbg/index.js:90:9)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
    at process._tickCallback (node.js:419:13)
```

**Comment by caspervonb** [comment]
Hi @marekventur, things have moved fairly fast and this looks like v0.11.x. Try upgrading first?

**Comment by marekventur** [comment]
Excellent, thanks, I will try that.

**Comment by caspervonb** [comment]
Also, since things are relative to the current working directory you probably would want to cd into that build directory and serve things from there.

```sh
cd static/build
chrome ...
amok index.js
```

**Comment by marekventur** [comment]
just realised, I'm on 0.13.8 so it's the most current version. It's still happening.

**Comment by caspervonb** [comment]
I see chrome is open, but there a tab open with the correct url (localhost:9966 if using internal server)?

**Comment by caspervonb** [comment]
Actually a better guess would be that the inspector is open on the tab? (chrome dev tools)

**Comment by marekventur** [comment]
oh, I didn't know I had to do that! The error went away now... The documentation was a bit vague on how to use it with a running chrome, thanks for clearing that up :)

**Comment by barneycarroll** [comment]
BTW, do we have to forego dev tools debugging completely? …Or is it possible to tunnel into the debugging process elsewhere?

**Comment by caspervonb** [comment]
So if you open the inspector after the connection has been established, the socket connection will be terminated, but it's not considered a fatal error, instead we will simply try to reconnect at an interval, which will succeed once the inspector is closed again, so you can do context switching as before, between your editor and dev tools.
