### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by corysimmons** [caspervonb/amok#64]
![](http://i.imgur.com/LOsEqqt.png)

**Comment by caspervonb** [comment]
Accidentally added a CNAME record on the apex domain instead of a subdomain, should be alright as soon as the DNS refreshes again.

**Comment by caspervonb** [comment]
Restored, thanks.

**Comment by corysimmons** [comment]
:+1:

**Comment by corysimmons** [comment]
As a side-issue, are there supposed to be images or something in these whitespace areas?

![](http://i.imgur.com/IiHyABL.png)

**Comment by caspervonb** [comment]
Yeah that was the intent of the layout, just haven't gotten to the graphical design part.

**Comment by caspervonb** [comment]
Basically there's still a ton left to do on the site, just *ok* is not good enough, it has to be awesome ;)

**Comment by corysimmons** [comment]
Maybe center align them while you wait on the graphics? :)

**Comment by caspervonb** [comment]
Made them full width, and yeah it does look better ;)
