### ISSUE TITLE
Support Chrome Canary

### ISSUE THREAD

**Issue by SamLebarbare** [caspervonb/amok#65]
The executable path is different for canary:
\Google\Chrome SxS\Application\chrome.exe

**Comment by caspervonb** [comment]
What would the usage look like?
`--client chrome-canary`?

What about the other release channels?

**Comment by caspervonb** [comment]
Just FYI, in the meantime you can pass any executable to the `--client` option.

**Comment by caspervonb** [comment]
See #75
