### ISSUE TITLE
Can amok be used with browser-sync?

### ISSUE THREAD

**Issue by cachaito** [caspervonb/amok#71]
Hello Again @caspervonb :relaxed:
I'd ask if Amok can be used in apps like this: git@gitlab.com:cachaito/test_watchify_BrowserSync.git
It's a simple representation of structure and tools I'm using (Browserify + watchify + Mithril MVC).
I've looked at amok-examples but no clue :flushed: 
The command `amok --client chrome --compiler browserify src/app.js -v` doesn't work.

BTW. If I understand correctly You push idea to keep compilers path in PATH variable or install it globally? How about reading projects node_modules and then other options You've mentioned [here](https://github.com/caspervonb/amok/pull/49)?

**Comment by caspervonb** [comment]
Hey @cachaito 

> I'd ask if Amok can be used in apps like this: git@gitlab.com:cachaito/test_watchify_BrowserSync.git

Can't clone the repository, please check the access rights? :smile: 

> BTW. If I understand correctly You push idea to keep compilers path in PATH variable or install it globally? How about reading projects node_modules and then other options You've mentioned here?

So we don't look in node_modules, because there is no reason to do so in my opinion, because `npm run` does add `$(npm bin)` to `PATH` so it should work out of the box without resorting to nasty hacks in the code, npm is technically domain specific and so you can't assume there will be npm_modules unless npm run is used, so it works out quite well to just do nothing special.

Makes sense?

**Comment by cachaito** [comment]
@caspervonb it's odd - this repo is public already... Please try with this link: https://gitlab.com/cachaito/test_watchify_BrowserSync.git

Feel free if You want use this (very simple) test repo. I hope it helps someone!

**Comment by caspervonb** [comment]
Http works, I'll have a look shortly :+1:

**Comment by caspervonb** [comment]
Sorry it's taking forever for me to get back to this, trying to get a stable release out :smile:

**Comment by cachaito** [comment]
I'm glad that You remember :-) You don't know how uncomfortable is working with watchify and browserify in Windows environment when You want to ditch a Gulp (some kind of my joke)

**Comment by cachaito** [comment]
I'm glad that You remember :-) You don't know how uncomfortable is working with watchify / browserify and BrowserSync in Windows environment when You want to ditch a Gulp (some kind of my joke)

**Comment by caspervonb** [comment]
Example is a bit convoluted, want to keep manually building with watchify or let amok handle it?

**Comment by cachaito** [comment]
Of course if Amok can handle it, why set it manually?

2015-06-04 14:09 GMT+02:00 Casper Beyer <notifications@github.com>:

**Comment by caspervonb** [comment]
Browserify can be run after amok with --proxy couldn't it?

**Comment by cachaito** [comment]
Hi Casper, yes it should. May I ask why it is a important issue?

2015-06-15 22:34 GMT+02:00 Casper Beyer <notifications@github.com>:

**Comment by caspervonb** [comment]
Basically you should be able to do this

```sh
$ node server.js
$ browser-sync ...
$ amok <browser-sync-url>
```

**Comment by caspervonb** [comment]
This works, basically you don't want browser-sync to open the browser as the rules described in `getting_started.md` apply, but the minimum requirements for amok to work is just to have a browser it can connect to.

```sh
browser-sync --server
amok --browser chrome --debug-port 4000 http://localhost:3000
amok --browser chromium --debug-port 4001 http://localhost:3000
```

It's a bit harder to get multiple tabs in the same browser process, each instance of amok will make a connection to a page but the matching is currently just the first url that is strict equal.

So this

```sh
amok --browser chrome http://localhost:3000
amok --browser chrome http://localhost:3000
```

Will open two tabs, but both are likely to connect to the first tab.

**Comment by caspervonb** [comment]
I have reverted to one browser instance per instance of amok, meaning 

```sh
browser-sync --server
amok --browser chrome --debug-port 4000 http://localhost:3000
amok --browser chrome --debug-port 4001 http://localhost:3000
```

Will work too.
