### ISSUE TITLE
Allow custom location of chrome executable

### ISSUE THREAD

**Issue by fibric** [caspervonb/amok#75]
I have all my browsers installed via `brew cask install google-chrome-beta`
amok assumes my chrome is placed in [/Applications](https://github.com/caspervonb/amok/blob/335d4ff32fc8e269f6edf552571556d769771366/lib/open.js#L27) but it isnt there. My Chrome is here: /opt/homebrew-cask/Caskroom/google-chrome-beta/latest/Google\ Chrome.app

How can I specify the correct location of chrome on my machine?

**Comment by fibric** [comment]
I symlinked chrome for now but that is not what I want tbh.

**Comment by barneycarroll** [comment]
@caspervonb sniff agent argument for path-like and look there? TBH current API is kinda pre-emptive sugar

**Comment by caspervonb** [comment]
So I was planning to search PATH in addition to the default install paths on windows and mac for the executable, should be a viable fix?

**Comment by caspervonb** [comment]
Is there a convention on this? (thinking of karma, testling, etc)

**Comment by caspervonb** [comment]
Thinking it'll go something like this

- Allow explicit override (e.g setting `CHROME_BIN` will short circuit the lookup and use it's value)
- Search in PATH on Windows and OS X (Linux already does it, makes sense and it makes things uniform)
- Finally, as a fallback search in default install directories.

**Comment by fibric** [comment]
@caspervonb 
sounds pretty good to me. we could use the same variable pattern for other browser too if they implement debug protocol (i guess Firefox will do and Spartan too).
