### ISSUE TITLE
Getting tests to pass on CI

### ISSUE THREAD

**Issue by caspervonb** [caspervonb/amok#83]
Trying to get the amok tests running with CI (codeship, but results are the same with travis and drone) but so far no luck at all.

Even an extremely simple test case with just spawning chrome and waiting for it to request the URL  just hangs indefinitely, if anyone has any ideas on how to resolve this that'd be amazing.

```js
var child = require('child_process');
var test = require('tape');
var http = require('http');

test('chrome', function(test) {
  var server = http.createServer();

  server.on('listening', function() {
    server.on('request', function() {
      test.end('request made');
    });

    var ps = child.spawn('/usr/bin/google-chrome', ['http://localhost:8000']);

    ps.stderr.pipe(process.stderr);
    ps.stdout.pipe(process.stderr);
  });

  server.listen(8000);
});
```

I'm making the assumption that it's due to GLX not being available with xvfb, but don't have much to go on here, no useful log info from the chrome process

**Comment by caspervonb** [comment]
So I'm continuing with Codeship primarily because they have easy SSH access to the container.

Poking around
```sh
$ xdpyinfo
name of display:    :99.0
version number:    11.0
vendor string:    The X.Org Foundation
vendor release number:    11501000
X.Org version: 1.15.1
maximum request size:  16777212 bytes
motion buffer size:  256
bitmap unit, bit order, padding:    32, LSBFirst, 32
image byte order:    LSBFirst
number of supported pixmap formats:    6
supported pixmap formats:
    depth 1, bits_per_pixel 1, scanline_pad 32
    depth 4, bits_per_pixel 8, scanline_pad 32
    depth 8, bits_per_pixel 8, scanline_pad 32
    depth 16, bits_per_pixel 16, scanline_pad 32
    depth 24, bits_per_pixel 32, scanline_pad 32
    depth 32, bits_per_pixel 32, scanline_pad 32
keycode range:    minimum 8, maximum 255
focus:  PointerRoot
number of extensions:    24
    BIG-REQUESTS
    Composite
    DAMAGE
    DOUBLE-BUFFER
    DPMS
    DRI3
    GLX
    Generic Event Extension
    MIT-SCREEN-SAVER
    MIT-SHM
    Present
    RECORD
    RENDER
    SECURITY
    SGI-GLX
    SHAPE
    SYNC
    X-Resource
    XC-MISC
    XFIXES
    XInputExtension
    XKEYBOARD
    XTEST
    XVideo
default screen number:    0
number of screens:    1

screen #0:
  dimensions:    2500x2500 pixels (635x635 millimeters)
  resolution:    100x100 dots per inch
  depths (6):    16, 1, 4, 8, 24, 32
  root window id:    0x12e
  depth of root window:    16 planes
  number of colormaps:    minimum 1, maximum 1
  default colormap:    0x20
  default number of colormap cells:    64
  preallocated pixels:    black 0, white 65535
  options:    backing-store WHEN MAPPED, save-unders NO
  largest cursor:    2500x2500
  current input event mask:    0x0
  number of visuals:    61
```

**Comment by caspervonb** [comment]
Alright, progress, well at the very least there's a fatal error showing up

```sh
$ /usr/bin/google-chrome
[19245:19245:0610/195242:ERROR:browser_main_loop.cc(219)] Gtk: Locale not supported by C library.
	Using the fallback 'C' locale.
Xlib:  extension "RANDR" missing on display ":99.0".
Fontconfig warning: ignoring UTF-8: not a valid region tag
Xlib:  extension "RANDR" missing on display ":99.0".
failed to create drawable
[19349:19349:0610/195244:ERROR:gl_surface_glx.cc(643)] glXCreatePbuffer failed.
[19349:19349:0610/195244:ERROR:gpu_info_collector.cc(27)] gfx::GLContext::CreateOffscreenGLSurface failed
[19349:19349:0610/195244:ERROR:gpu_info_collector.cc(89)] Could not create surface for info collection.
[19349:19349:0610/195244:ERROR:gpu_main.cc(411)] gpu::CollectGraphicsInfo failed (fatal).
[19349:19349:0610/195244:ERROR:sandbox_linux.cc(340)] InitializeSandbox() called with multiple threads in process gpu-process
[19349:19349:0610/195244:ERROR:gpu_child_thread.cc(163)] Exiting GPU process due to errors during initialization
```

**Comment by caspervonb** [comment]
Alright so, Firefox works, which means that xvfb is fine it's just chrome that isn't launching properly.

**Comment by caspervonb** [comment]
Poking around some more, now the test actually passes if run directly when ssh'ing to codeship, but is still pending when doing the CI build.

**Comment by caspervonb** [comment]
So the first time running google-chrome it just hangs without opening the URL, the second time starting the process it works, that's the reason it eventually worked via SSH.

My immediate hunch is profile first run issues.

**Comment by caspervonb** [comment]
Yeah so it's due to the first run dialog, running with --no-first-run and the test passes, makes sense in hindsight as the dialog will prelude the browser window.

**Comment by caspervonb** [comment]
Last blocker is chokidar, which apparently doesn't work with docker unless polling is used.

**Comment by caspervonb** [comment]
Just a session over ssh with a simple watch logger

```sh
rof@railsonfire_1acc69a0-059c-0133-dc41-2a4b444e51a1_94d0acddd428:~/clone$ nvm use 0.12
Now using node v0.12.5 (npm v2.11.2)
rof@railsonfire_1acc69a0-059c-0133-dc41-2a4b444e51a1_94d0acddd428:~/clone$ node test &
[1] 21732
rof@railsonfire_1acc69a0-059c-0133-dc41-2a4b444e51a1_94d0acddd428:~/clone$ watcher ok
touch file.txt
rof@railsonfire_1acc69a0-059c-0133-dc41-2a4b444e51a1_94d0acddd428:~/clone$ rename file.txt

rof@railsonfire_1acc69a0-059c-0133-dc41-2a4b444e51a1_94d0acddd428:~/clone$ vim file.txt
rename file.txt~
rename file.txt
change file.txt
rename file.txt~
rename .file.txt.swp
```

fs.watch seems to be working fine

**Comment by caspervonb** [comment]
So, editing with vim works in the CI environment but using fs.writeFileSync does not emit any events.

**Comment by caspervonb** [comment]
I'm fairly certain this is both `chokidar` and `fs.watch` behaving very differently on Linux than OS X and Windows. It seems to pick up atomic writes (which are directory changes) but not file writes which *might* not be directory changes with `libinotify`.

Also possible is that we're falling back to `kqueue` or something else on codeship, because my primary development environment before going OS X has been fedora.

Setting up a Fedora VM and I'll know more then, tests haven't been run on Linux in a while either which is a bad thing and needs to be done.

**Comment by caspervonb** [comment]
Fedora VM works as intended, so its something different about the CI environment.

**Comment by caspervonb** [comment]
Contacted codeship support, as I suspected `libinotify` is not available, and fallback is the most likely cause.

**Comment by caspervonb** [comment]
From Codeship support, it will be added.

> Alright, I'll prepare a PR and will push the new image once it's ready.

**Comment by caspervonb** [comment]
`libinotify` is apparently in the new images but the tests still stall.
Might have to give up on the cloud hosted CI approach and just roll with jenkins.

**Comment by caspervonb** [comment]
**Success**, sort of.

After a lot of head bashing, I've finally gotten the tests to run in Circle-CI.

![screen shot 2015-07-26 at 07 01 41](https://cloud.githubusercontent.com/assets/157787/8891634/3f1414e6-3365-11e5-9580-1ff11e98599f.png)

Overall build fails due to environmental issues but at-least it's testable on one browser (google-chrome).

On Appcelerator, the situation essentially the same, except there are some additional make issues.
![screen shot 2015-07-26 at 07 15 47](https://cloud.githubusercontent.com/assets/157787/8891651/2faa9d6c-3366-11e5-9014-68a809cc176b.png)

So summary, the tests run, semi-trivial environment configuration to sort out.

**Comment by cowboyd** [comment]
@caspervonb So what did you do to get it working?
