### ISSUE TITLE
Use with webpack and babel

### ISSUE THREAD

**Issue by xgrommx** [caspervonb/amok#84]
Hello @caspervonb I tried use example with webpack and babel but this one doesn't work. Could you create a simple example which will be working?

**Comment by caspervonb** [comment]
Updated the amok-examples repo to 1.x

**Comment by xgrommx** [comment]
@caspervonb I see, but livereload doesn't work even if I changed text ```Hello```

**Comment by caspervonb** [comment]
Just re-tested on mac and windows, it's working.

The most likely cause, is that if chrome is already running when running amok, it has to be listening on port 9222. Add additional options like a profile to CHROME_FLAGS to force a new process to be spawned.

```sh
CHROME_FLAGS="user-data-dir=path/to/somewhere"
```

**Comment by xgrommx** [comment]
One question. What is ```path/to/somewhere```?

**Comment by caspervonb** [comment]
Any directory path the file system

**Comment by xgrommx** [comment]
Probably a reason why doesn't working because in my environment settings existed AMOK_CLIENT. I removed it and livereloading looks like working. I think this issue could be closed.

**Comment by caspervonb** [comment]
Great ;)

**Comment by xgrommx** [comment]
Sorry, I have one question. What is an url I need include in my index.html if my source contains in src folder? In react-hot-loader it will be:

```html
<script src="/static/bundle.js"><script>
```

**Comment by xgrommx** [comment]
I realize why this doesn't work. At my package.json I need use ```\\``` separator because I have Windows.

```js
"scripts": {
    "start": "amok --hot --browser chrome --compiler webpack src\\index.js"
  }
```

**Comment by caspervonb** [comment]
> What is an url I need include in my index.html if my source contains in src folder?

The output bundle will be the same as the entry path, so src/foo/bar.js becomes src/foo/bar.js

> I realize why this doesn't work. At my package.json I need use \\ separator because I have Windows.

In this case it might make more sense to cd/chdir into to src.
