### ISSUE TITLE
Add license.markdown 

### ISSUE THREAD

**Issue by falafflepotatoe** [caspervonb/amok#9]
can you put a license? i really want to make a brackets plugin for this

**Comment by Pomax** [comment]
[package.json](https://github.com/caspervonb/amok/blob/master/package.json#L37) tells us that the current version of the code is licensed under an MIT license.

**Comment by caspervonb** [comment]
Correct, MIT license.

**Comment by caspervonb** [comment]
@falafflepotatoe How do you intend for the plugin to work? I did consider it previously, then concluded that pretty much all editors allow you to run configure commands already, and its easy to integrate that way.

**Comment by falafflepotatoe** [comment]
pretty much that, and possibley code a qui to allow the user to configure via gui instead of via args or conf files.
