### ISSUE TITLE
Regressions on Windows with v1.0.0-4

### ISSUE THREAD

**Issue by caspervonb** [caspervonb/amok#93]
Introduced a regression on windows with 1.0.0-4 that basically messes up the file lookup making watch and hot patches fail by not finding the related file, I was cutting the release to get the internal dependencies on semver instead of git/master.

#91 replaces chokidar with fs.watch, and will fix these regressions also.

**Comment by stereokai** [comment]
you are very dedicated, thank you for keeping us posted, even on these small issues.

**Comment by caspervonb** [comment]
Appreciate it, I try :sweat:

Ended up just patching it in master, leaving this issue open until a stable release is out that works for windows but you should be relatively safe doing `npm install caspervonb/amok#master`

**Comment by caspervonb** [comment]
Pushed out another permitter, was aiming for the next version to be 1.0.0 as i intend to properly track releases from that point. Anyhow closing as resolved, I've battered the tests for hours couldn't get it to fail.

**Comment by stereokai** [comment]
@caspervonb Thanks man, I appreciate it a lot!
