### ISSUE TITLE
Use fnmatch like matching for selecting target

### ISSUE THREAD

**Issue by caspervonb** [caspervonb/amok#94]
Currently, target selection is done by strict url equality, which is very strict and won't even match `http://localhost:8000` to `http://localhost:8000/`

Would be more appropriate to select by `fnmatch` like glob patterns. For example `http://localhost:8000/*` would match any path with that host (hostname and port)

**Comment by stereokai** [comment]
Do you expect amok to process and hot patch requests to js files from the webpage/app?

**Comment by caspervonb** [comment]
> Do you expect amok to process and hot patch requests to js files from the webpage/app?

Not sure what you're asking here.

This is strictly about how the target page is selected, currently its strict equality meaning `http://localhost:8000/` and `http://localhost:8000` won't match, confusing the heck out of users.

**Comment by stereokai** [comment]
> http://localhost:8000/* would match any path with that host (hostname and port)

I interpreted the `*` as accepting more than a single JS file under this address.

**Comment by caspervonb** [comment]
The match patterns chrome extensions seems like a good *match*

**Comment by stereokai** [comment]
Shouldn't be hard to implement - have you looked for any library that does this already?

**Comment by caspervonb** [comment]
It's fairly trival to implement but diddn't find a good clean implementation. `urlmatch` for example, if i remember correctly just diddn't work at all.

**Comment by stereokai** [comment]
Should be just a bit of regex work right?

**Comment by caspervonb** [comment]
Basically yeah.

**Comment by caspervonb** [comment]
Normalising instead d73956c963eb16e9322dbea377b3dccf8ac0ac91
