### ISSUE TITLE
Resolve relative *.html file paths into absolute file urls

### ISSUE THREAD

**Issue by caspervonb** [caspervonb/amok#95]
Currently, it's a bit cumbersome to open a file url, typically one would do

```sh
amok file://$PWD/index.html
```

More convenient would be to allow file paths ending with .html to be resolved into absolute urls.
```sh
amok index.html
```

**Comment by stereokai** [comment]
This is instead of passing a server URL?

**Comment by caspervonb** [comment]
Expanding html files into absolute file urls, e.g `/.html$/` entries into `url.resolve('file://, path.resolve(entry))`

**Comment by stereokai** [comment]
Would you be able to do `amok /.html$/ ...`?

**Comment by caspervonb** [comment]
```
$ amok foobar.html
```

would be equivalent to

```
$ amok file://$PWD/foobar.html
```

**Comment by stereokai** [comment]
So it should be in lib, not in bin then.

**Comment by caspervonb** [comment]
resolution is done in `browser` b42d5dd9a6a01b99d92c138b8ac791c442b0d633
