### ISSUE TITLE
Problem installing on Windows 8.1

### ISSUE THREAD

**Issue by Harshdand** [caspervonb/amok#99]
Hi,

I am unable to install amok on my windows pc here is the error that I get.
I am assuming that the error occurs because of the beta version of python (3.5.0b3)

>C:\Users\harsh\Apps\Tutorial\angularjs>npm install amok -g
npm WARN optional dep failed, continuing fsevents@0.3.6
 bufferutil@1.1.0 install C:\Users\harsh\AppData\Roaming\npm\node_modules\amok\
node_modules\rdbg\node_modules\ws\node_modules\bufferutil
 node-gyp rebuild
C:\Users\harsh\AppData\Roaming\npm\node_modules\amok\node_modules\rdbg\node_modu
les\ws\node_modules\bufferutil>node "C:\Program Files (x86)\nodejs\node_modules\
npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack TypeError: Invalid Version: 3.5.0b3
stack     at new SemVer (C:\Program Files (x86)\nodejs\node_modules\npm\node_mod
ules\semver\semver.js:273:11)
gyp ERR! stack     at compare (C:\Program Files (x86)\nodejs\node_modules\npm\no
de_modules\semver\semver.js:456:10)
gyp ERR! stack     at gte (C:\Program Files (x86)\nodejs\node_modules\npm\node_m
odules\semver\semver.js:505:10)
gyp ERR! stack     at cmp (C:\Program Files (x86)\nodejs\node_modules\npm\node_m
odules\semver\semver.js:522:22)
gyp ERR! stack     at Comparator.test (C:\Program Files (x86)\nodejs\node_module
s\npm\node_modules\semver\semver.js:592:10)
gyp ERR! stack     at testSet (C:\Program Files (x86)\nodejs\node_modules\npm\no
de_modules\semver\semver.js:926:17)
gyp ERR! stack     at Range.test (C:\Program Files (x86)\nodejs\node_modules\npm
\node_modules\semver\semver.js:918:9)
gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_module
s\node-gyp\lib\configure.js:94:17
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:646:7)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\nod
e_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\harsh\AppData\Roaming\npm\node_modules\amok\node_modules\r
dbg\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
npm WARN optional dep failed, continuing bufferutil@1.1.0

 >utf-8-validate@1.1.0 install C:\Users\harsh\AppData\Roaming\npm\node_modules\a
mok\node_modules\rdbg\node_modules\ws\node_modules\utf-8-validate
 node-gyp rebuild
C:\Users\harsh\AppData\Roaming\npm\node_modules\amok\node_modules\rdbg\node_modu
les\ws\node_modules\utf-8-validate>node "C:\Program Files (x86)\nodejs\node_modu
les\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack TypeError: Invalid Version: 3.5.0b3
gyp ERR! stack     at new SemVer (C:\Program Files (x86)\nodejs\node_modules\npm
\node_modules\semver\semver.js:273:11)
gyp ERR! stack     at compare (C:\Program Files (x86)\nodejs\node_modules\npm\no
de_modules\semver\semver.js:456:10)
gyp ERR! stack     at gte (C:\Program Files (x86)\nodejs\node_modules\npm\node_m
odules\semver\semver.js:505:10)
gyp ERR! stack     at cmp (C:\Program Files (x86)\nodejs\node_modules\npm\node_m
odules\semver\semver.js:522:22)
gyp ERR! stack     at Comparator.test (C:\Program Files (x86)\nodejs\node_module
s\npm\node_modules\semver\semver.js:592:10)
gyp ERR! stack     at testSet (C:\Program Files (x86)\nodejs\node_modules\npm\no
de_modules\semver\semver.js:926:17)
gyp ERR! stack     at Range.test (C:\Program Files (x86)\nodejs\node_modules\npm
\node_modules\semver\semver.js:918:9)
gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_module
s\node-gyp\lib\configure.js:94:17
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:646:7)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\nod
e_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\harsh\AppData\Roaming\npm\node_modules\amok\node_modules\r
dbg\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
npm WARN optional dep failed, continuing utf-8-validate@1.1.0

**Comment by caspervonb** [comment]
> The --no-optional argument will prevent optional dependencies from being installed.
> https://docs.npmjs.com/cli/install

You can try installing with `--no-optional` which will skip optional dependencies in `ws`, not sure how it will affect performance but at the very least it won't install the bits that requires native compilation with node-gyp.

```sh
npm install amok --no-optional --global
```

You should probably report this upstream with node-gyp too.
